virtual_modifiers:
  - F13

modmap:
  - remap:
      KEY_MUHENKAN:
        held: F13
        alone: KEY_MUHENKAN
        free_hold: true

keymap:
  - remap:
      F13-h: Left
      F13-j: Down
      F13-k: Up
      F13-l: Right
      F13-o: Backspace
      F13-n: Delete
      F13-Space: Enter
      F13-a: Home
      F13-e: End
      F13-q: Esc
